// <auto-generated />
namespace CompleteUtterGarbage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rolesareclosetoready : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rolesareclosetoready));
        
        string IMigrationMetadata.Id
        {
            get { return "201802092007207_roles are close to ready"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
